apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: amitfegade121/eureka-server:1.0
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
spec:
  selector:
    app: eureka-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
      nodePort: 31000
